docusaurus:
  work-directory: D:\AIO #工作位置
  note-repo-url: https://gitee.com/wangziming707/note.git
  project:
    name: personal-note-website # 项目名称
    version: 3.5.2 #docusaurus项目版本
    static-path: D:\AIO\static\note #在静态资源映射中的相对地址
    docusaurus-config-path: classpath:docusaurus-config/docusaurus.config.js
    sidebars-config-path: classpath:docusaurus-config/sidebars.js
    plugin-dependencies: # 项目需要的依赖
      - "@node-rs/jieba@1.10.0"
      - "docusaurus-lunr-search@3.3.2"
      - "remark-math@6.0.0"
      - "rehype-katex@7.0.0"
  note-picture:
    local-request-path: http://localhost:80/image # 本地项目提供的图片访问根路径
    cloud-request-path: https://gitee.com/wangziming707/note-pic/raw/master/img # 图床访问根路径
    repo-url: https://gitee.com/wangziming707/note-pic.git # 图床git仓库
    static-path: D:\AIO\static\image #在本地静态资源映射中的相对地址
    img-location: /img  #图片在远程仓库中的位置

spring:
  application:
    name: aio
  datasource:
    url: jdbc:mysql://localhost:3306/aio
    username: root
    password: 123456

momo:
  token: 2941df5f80f92f9c3a5256d5762b3c30a0eb82256f269e82c1ff15a203b55096
  notepad:
    local-id: 1
    max-count: 7

logging:
  level:
    root: INFO
    com.wzm.aio.api: DEBUG
    expect4j: OFF

springdoc:
  swagger-ui:
    path: /swagger.html
