spring:
  config:
    import: classpath:token.properties
  application:
    name: aio
  datasource:
    url: jdbc:mysql://localhost:3306/aio
    username: root
    password: 123456
docusaurus:
  work-directory: D:\AIO #工作位置
  note-repo-url: https://gitee.com/wangziming707/note.git
  project:
    name: personal-note-website # 项目名称
    version: 3.5.2 #docusaurus项目版本
    static-path: D:\AIO\static\note #在静态资源映射中的相对地址
    docusaurus-config-path: classpath:docusaurus-config/docusaurus.config.js
    sidebars-config-path: classpath:docusaurus-config/sidebars.js
    plugin-dependencies: # 项目需要的依赖
      - "@node-rs/jieba@1.10.0"
      - "docusaurus-lunr-search@3.3.2"
      - "remark-math@6.0.0"
      - "rehype-katex@7.0.0"
  note-picture:
    local-request-path: http://localhost:80/image # 本地项目提供的图片访问根路径
    cloud-request-path: https://gitee.com/wangziming707/note-pic/raw/master/img # 图床访问根路径
    repo-url: https://gitee.com/wangziming707/note-pic.git # 图床git仓库
    static-path: D:\AIO\static\image #在本地静态资源映射中的相对地址
    img-location: /img  #图片在远程仓库中的位置

open-api:
  time-out: 30  # s
  max-memory-size: 2  # MB
  enable-log : true

  momo:
    base-url: https://open.maimemo.com/open/api/v1/notepads
    headers:
      Authorization: "Bearer ${token.momo}"
    notepad-max-count: 7
  fr-dic:
    base-url: https://api.frdic.com/api/open/v1/studylist
    headers:
      Authorization: ${token.token.dr-dic}
  openai:
    token: ${token.openai}
    proxy-host: localhost
    proxy-port: 7890
    model: gpt-3.5-turbo
    temperature: 0.4
    max-tokens: 20000


  local-base-url: http://localhost:8080

logging:
  level:
    root: INFO
    com.wzm.aio.api: DEBUG
    expect4j: OFF

springdoc:
  swagger-ui:
    path: /swagger.html
project:
  init:
    momo-pull: false
    fr-sync: false
  closed:
    momo-push: false
serialized:
  file:
    path: D:\AIO\serialized


management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    beans:
      enabled: true

