version: '3.7'
# truenas设置nfs共享时，将mapall 设置为 root
volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.101,rw"
      device: ":/mnt/main-pool/dockers/nextcloud"
  mariadb:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.101,rw"
      device: ":/mnt/main-pool/dockers/mariadb"

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=wang998321 # 按需修改
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.2.104
      - TZ=Asia/Shanghai
    ports:
      - "88:80"

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    user: "0:0"
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
    environment:
      - TZ=Asia/Shanghai

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    # 下面的command与官网略有不同。它将有助于避免MYSQL数据库的4047报错。
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wang998321 # 按需修改
      - MYSQL_PASSWORD=wang998321  # 按需修改
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=Asia/Shanghai
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
  # docker cp prometheus:/etc/prometheus /docker
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
# 修改 /etc/prometheus/prometheus.yml
# 在最后添加上：
#     scrape_configs:
#      - job_name: 'proxmox'
#        metrics_path: /pve
#        static_configs:
#        - targets: ['192.168.2.99:9221']