version: '3.7'

volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.101,rw"
      device: ":/mnt/main-pool/media"
  jav:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.101,rw"
      device: ":/mnt/main-pool/jav"
  downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.101,rw"
      device: ":/mnt/download-pool/downloads"

services:
  nas-tools: #默认账户密码: admin /password
    container_name: nas-tools
    hostname: nas-tools
    image: diluka/nas-tools:2.9.1
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nas-tools/config:/config
      - media:/media-library
      - downloads:/downloads
    environment:
      NASTOOL_AUTO_UPDATE: "false"
      PUID: 0
      PGID: 0

  # tracker列表地址: https://github.com/XIU2/TrackersListCollection?tab=readme-ov-file
  # 对于新建，需要执行下面命令改变默认网卡：
  # ip route del default
  # ip route add default via <gateway-ip-of-eth1> dev eth1
  qbittorrent:  # 通过docker logs qbittorrent 查看默认账户密码 容器端口 6881 8989
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: always
    environment:
      WEBUI_PORT: 8989
      TORRENTING_PORT: 6881
      PUID: 0
      PGID: 0
      TZ: Asia/Shanghai
    ports:
      - "6881:6881"
      - "8989:8989"
      - "6881:6881/udp"
    volumes:
      - ./qbittorrent/config:/config
      - downloads:/downloads
      - media:/media-library
  qbittorrent-p:
    image: johngong/qbittorrent:latest
    container_name: qbittorrent-p
    ports:
      - "8990:8990"
      - "6882:6881"
      - "6882:6881/udp"
    environment:
      - QB_WEBUI_PORT=8990
      - QB_EE_BIN=false
      - UID=0
      - GID=0
      - UMASK=022
    volumes:
      - ./qbittorrent-p/config:/config
      - downloads:/Downloads
    restart: always
  peerbanhelper:
    image: ghostchu/peerbanhelper:v7.1.5
    restart: always
    container_name: "peerbanhelper"
    volumes:
      - ./peerbanhelper/data:/app/data
    ports:
      - "9898:9898"
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
  # mkdir -p /docker/emby-kx/system
  # docker cp emby-kx-server:/system/dashboard-ui /docker/emby-kx/system/dashboard-ui
  emby-kx:
    image: lovechen/embyserver:latest
    container_name: emby-kx-server
    restart: always
    ports:
      - "8096:8096"
    environment:
      UID: 0
      GID: 0
      GIDLIST: 100,101
    volumes:
      - ./emby-kx/config:/config
      - ./emby-kx/fonts:/usr/share/fonts
      - media:/media
      - ./emby-kx/system/dashboard-ui:/system/dashboard-ui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # mkdir -p /docker/emby/system
  # docker cp emby-server:/system/dashboard-ui /docker/emby/system/dashboard-ui
  emby:
    image: emby/embyserver:latest
    container_name: emby-server
    restart: always
    environment:
      UID: 0
      GID: 0
      GIDLIST: 100,101
    volumes:
      - ./emby/config:/config
      - jav:/media
      #- ./emby/system/dashboard-ui:/system/dashboard-ui
    ports:
      - "8097:8096"

  chinesesubfinder:
    container_name: chinesesubfinder
    hostname: chinesesubfinder
    image: allanpk716/chinesesubfinder:latest
    restart: always
    privileged: true
    volumes:
      - ./chinesesubfinder/config:/config
      - ./chinesesubfinder/browser:/root/.cache/rod/browser
      - media:/media
    environment:
      PUID: 0
      PGID: 0
      PERMS: "true"
      TZ: Asia/Shanghai
      UMASK: 022
    ports:
      - "19035:19035"
      - "19037:19037"
    logging:
      driver: json-file
      options:
        max-size: "100m"
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: always
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/shanghai
      AUTO_UPDATE: "true"
    ports:
      - "9117:9117"
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"    # Portainer Web UI 端口
      - "8000:8000"    # 可选：用于 Portainer Agent 的 TCP 端口
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 允许 Portainer 访问 Docker 引擎
      - ./portainer/data:/data  # 存储 Portainer 数据
  javsp:
    image: kxhubs/javsp:0.3  # 镜像名称
    container_name: javsp  # 容器名称
    restart: always  # 自动重启策略
    environment:
      CRON_TIME: "0 * * * *"  # "*/5 * * * *"  # 环境变量，定时任务时间
      PUID: 0
      PGID: 0
    volumes:
      - ./javsp/core/config.ini:/app/core/config.ini  # 必须的配置文件映射
      - downloads:/downloads
      - media:/media
  xunlei:
    image: cnk3x/xunlei
    container_name: xunlei
    privileged: true
    restart: always  # 自动重启策略
    ports:
      - "2345:2345"
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - ./xunlei/data:/xunlei/data
      - downloads:/xunlei/downloads
  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
    volumes:
      - ./auto-bangumi/config:/app/config
      - downloads:/downloads
      - media:/media
    ports:
      - "7892:7892"
    network_mode: bridge
    restart: always
    dns:
      - 223.5.5.5
    environment:
      - TZ=Asia/Shanghai
      - PGID=0
      - PUID=0
      - UMASK=022
  # tmm中文问题解决，进入docker容器,执行下面命令：
  # apt-get install locales
  # dpkg-reconfigure locales
  tinymediamanager:
    image: tinymediamanager/tinymediamanager:latest
    container_name: tinymediamanager
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - ALLOW_DIRECT_VNC=false
      - LC_ALL=zh_CN.UTF-8 # force UTF8
      - LANG=zh_CN.UTF-8   # force UTF8
      - PASSWORD=wang998321
    volumes:
      - ./tinymediamanager/data:/data
      - downloads:/downloads
      - media:/media
    ports:
      #- "5900:5900" # VNC port
      - "4000:4000" # Webinterface
    restart: always